### PR TITLE
Fix ios class rename bug

### PR DESCRIPTION
**Pull request by kirillpisarev**
Fix 3.1.0 update bug

### CODE REVIEW

**Comment by harryrein3** [comment]
Why did you do this? Throwing off projects that used the old name.

**Comment by gabrielbull** [comment]
Why rename to RNSplashScreen though? If we were to prefix the library it should have been RCTSplashScreen to follow React Native's standard.

**Comment by orlein** [comment]
I've spent about 5 hours fixing this problem... Please merge.

**Comment by ZakZubair** [comment]
+1

**Pull request closed without merging**
