### PR TITLE
fix ios build and update docs

### LINKED ISSUE #250: Build failed on v.3.1.0
In new release there is a bug.
You forget to rename 
[SplashScreen show];
to RNSplashScreen in RNSplashScreen.m

And also in documentation for install i think you should update AppDelegate.m with rename #import "SplashScreen.h" to "RNSplashScreen.h"
Thanks.

### LINKED ISSUE #256: Do not upgrade
RCT_EXPORT_METHOD(show) {
    [SplashScreen show]; 
    //  [RNSplashScreen show];
}

brother，your code has bug。

### LINKED ISSUE #257: 'SplashScreen.h' file not found
version: **3.1.0**
You probably have not rebuilt the file: **libSplashScreen.a**

_The module is not working_

### LINKED ISSUE #258: Typo???
https://github.com/crazycodeboy/react-native-splash-screen/blob/2b96a49e3650daf7d732d3195005877034420a22/ios/RNSplashScreen.m#L52

SplashScreen --> RNSplashScreen

### LINKED ISSUE #260: iOS Build failed: unknown receiver 'SplashScreen'; did you mean 'RNSplashScreen'
Hi, I'm facing the following issue on version 3.1.0 with Xcode 9 while building iOS app
```
node_modules/react-native-splash-screen/ios/RNSplashScreen.m:52:6: unknown receiver 'SplashScreen'; did you mean 'RNSplashScreen'?
```

Looking at **RNSplashScreen.m:52:6**, I found this
```
RCT_EXPORT_METHOD(show) {
    [SplashScreen show];
}
```
When replacing **SplashScreen** by **RNSplashScreen** the build succeeds. But I'm wondering if it's the right way to go.

Thanks.

### LINKED ISSUE #263: [SplashScreen show] should be [RNSplashScreen show]
https://github.com/crazycodeboy/react-native-splash-screen/blob/2b96a49e3650daf7d732d3195005877034420a22/ios/RNSplashScreen.m#L52

### PR DESCRIPTION
**Pull request by danieloprado**
Fix #260  Fix #263 and Fix #257 Fix #258 Fix #256 Fix #250

### CODE REVIEW

**Comment by cayasso** [comment]
Hi, 
Any update on mergin this fix?

**Comment by ccjx** [comment]
Hi, can we have this PR merged soon as this is hitting my project as well.

**Comment by petterroea** [comment]
@crazycodeboy  :)

**Comment by jantemel** [comment]
+1

**Comment by imamatory** [comment]
+1

**Comment by rafaellincoln** [comment]
+1

**Comment by dancham86** [comment]
+1

**Comment by EsdrasEtrenne** [comment]
downgrade to 3.0.9 works but a merge wold be great

**Comment by flackou** [comment]
+1

**Comment by chrusart** [comment]
@EsdrasEtrenne in 3.1.0 are some crash fixes we encounter in production.
Before 3.1.0 we used own repo with fixes, now we use PR version.

**Comment by ttruongatl** [comment]
the PR should be great.

**Comment by RobPando** [comment]
+1

**Comment by rsmelo92** [comment]
+1

**Pull request merged**
