### PR TITLE
Fix class name after rename

### PR DESCRIPTION
**Pull request by dluksza**

### CODE REVIEW

**Comment by adrienthiery** [comment]
Latest version breaks without that change... @crazycodeboy

**Comment by ebaynaud** [comment]
Please create a release 3.1.1 with that one!

**Comment by craigcoles** [comment]
Would be awesome to get this merged, as the latest version is currently broken cc/ @crazycodeboy

**Comment by JackOddy** [comment]
Would be great to get this merged in!

**Comment by matyasfodor** [comment]
Here's a quick fix that can temporarily fix this until it's merged
```
sed -i -e "s/\[SplashScreen show\];/\[RNSplashScreen show\];/g" node_modules/react-native-splash-screen/ios/RNSplashScreen.m
```

**Comment by chrusart** [comment]
imho @matyasfodor 
```"react-native-splash-screen": "github:dluksza/react-native-splash-screen#85c4b6a3dac68ba690a046475b19e4a97dc096b7",```
would be a better quick fix, and better with own repo fork.

**Comment by kesha-antonov** [comment]
@crazycodeboy Waiting for get merged...

**Comment by yurikilian** [comment]
When will this fix be available at npm?

**Pull request closed without merging**
