### PR TITLE
add setTimeout 3 seconds of splash screen 

### PR DESCRIPTION
**Pull request by ahmadahmadi14**
I have added setTimeout 3 seconds of splash screen

### CODE REVIEW

**Comment by ohtangza** [comment]
To be merged with master, I think there should be some interface to pass in the `seconds` parameter. Not everyone using this library might not want to use **3** seconds.

**Comment by philolo1** [comment]
@ohtangza seems like he is only changing the example. So either merge or close it. I think @crazycodeboy can just close it, i think people will understand it anyway.

**Comment by ohtangza** [comment]
@philolo1 Oh, I misunderstood change. It seems this change is reasonable!

**Comment by techyrajeev** [comment]
Timeout should be configurable by user itself.

You can achieve the same thing with below code I guess.

Inside App.js
```
componentDidMount() {
     setTimeout(SplashScreen.hide,1000);
}
```

**Pull request closed without merging**
