### PR TITLE
Update README for 0.3.1 changes

### PR DESCRIPTION
**Pull request by iRoachie**
0.3.1 changes the package identifier to org.devio in commit https://github.com/crazycodeboy/react-native-splash-screen/commit/ed6df50d31b6bb8228998878edbe9d8ddbc7751a

This PR just updates in the installation instructions in the README

### CODE REVIEW

**Comment by mgtitimoli** [comment]
Great @iRoachie I was about to do the same when I saw your PR.

Don't you mind to add an entry of how to use with CocoaPods?

**Comment by iRoachie** [comment]
@mgtitimoli I'm not actually sure how cocoapods works (js developer). Maybe you could do it in another PR

**Comment by mgtitimoli** [comment]
JS dev here too :slightly_smiling_face:.

Basically the changes I'm saying can be split into two

`pod 'react-native-splash-screen', path: '../node_modules/react-native-splash-screen'`

1. Move the content under **Manual installation > IOS** to **Manual installation > IOS > With XCode**
2. Add a new section  **Manual installation > IOS > With CocoaPods** and place the following within:
```markdown
1. Add the plugin dependency to your Podfile:
`pod 'react-native-splash-screen', path: '../node_modules/react-native-splash-screen'`
2. Run pod install
```

As a side note, I recommend you to try CocoaPods, I found it cleaner than placing everything in the xcode project file.

**Comment by iRoachie** [comment]
@mgtitimoli Best to make another PR as it isn't in line with the 0.3.1 release

**Pull request merged**
